### ISSUE TITLE
"Cancel" on make file

### ISSUE THREAD

**Issue by Alexey-T** [pohmelie/cuda_ftp#3]
"Make new file"- press Cancel
console panel:
~~~
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cudatext/py/cuda_ftp/__init__.py", line 334, in action_new_file
    "Filename:", "",
TypeError: 'NoneType' object is not iterable
~~~

**Comment by pohmelie** [comment]
Thanks, I will fix this ASAP.
